param(
  [ValidateSet("deps", "full")]
  [string]$Mode = "deps",

  [switch]$Build,
  [switch]$Pull,
  [switch]$KeepManagerContainer
)

$ErrorActionPreference = "Stop"

$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$RepoRoot = Resolve-Path (Join-Path $ScriptDir "..")
$ComposeFile = Join-Path $RepoRoot "deploy\docker-compose.yml"
$EnvFile = Join-Path $RepoRoot ".env"
$DevOverrideFile = Join-Path $RepoRoot ".cache\dev-compose.override.yml"

function Write-Step {
  param([string]$Message)
  Write-Host ""
  Write-Host "==> $Message" -ForegroundColor Cyan
}

function Write-Info {
  param([string]$Message)
  Write-Host $Message -ForegroundColor Gray
}

function Read-DotEnv {
  param([string]$Path)
  $values = @{}
  if (-not (Test-Path $Path)) {
    return $values
  }

  foreach ($line in Get-Content $Path) {
    $trimmed = $line.Trim()
    if ($trimmed.Length -eq 0 -or $trimmed.StartsWith("#")) {
      continue
    }
    $idx = $trimmed.IndexOf("=")
    if ($idx -lt 1) {
      continue
    }
    $key = $trimmed.Substring(0, $idx).Trim()
    $value = $trimmed.Substring($idx + 1).Trim()
    if (($value.StartsWith('"') -and $value.EndsWith('"')) -or ($value.StartsWith("'") -and $value.EndsWith("'"))) {
      $value = $value.Substring(1, $value.Length - 2)
    }
    $values[$key] = $value
  }
  return $values
}

function Env-OrDefault {
  param(
    [hashtable]$Env,
    [string]$Key,
    [string]$Default
  )
  if ($Env.ContainsKey($Key) -and -not [string]::IsNullOrWhiteSpace($Env[$Key])) {
    return $Env[$Key]
  }
  return $Default
}

function Test-Command {
  param([string]$Name)
  $null -ne (Get-Command $Name -ErrorAction SilentlyContinue)
}

function Ensure-DevOverride {
  param([string]$Path)
  $dir = Split-Path -Parent $Path
  if (-not (Test-Path $dir)) {
    New-Item -ItemType Directory -Force -Path $dir | Out-Null
  }

  @"
# Generated by scripts/dev-up.ps1.
# Local Go development only: publish internal dependency ports to Windows.
services:
  loki:
    ports:
      - "3100:3100"
  tempo:
    ports:
      - "3200:3200"
  qdrant:
    ports:
      - "6333:6333"
      - "6334:6334"
"@ | Set-Content -Encoding UTF8 -Path $Path
}

function Invoke-DockerComposeQuiet {
  param(
    [string[]]$Args,
    [string]$WarnMessage
  )

  $oldErrorActionPreference = $ErrorActionPreference
  try {
    # Docker Compose writes progress/status lines to stderr on Windows.
    # With $ErrorActionPreference=Stop PowerShell can surface those lines as
    # NativeCommandError even when compose exits successfully.
    $ErrorActionPreference = "Continue"
    & docker compose @Args *> $null
    if ($LASTEXITCODE -ne 0 -and -not [string]::IsNullOrWhiteSpace($WarnMessage)) {
      Write-Host $WarnMessage -ForegroundColor Yellow
    }
  } finally {
    $ErrorActionPreference = $oldErrorActionPreference
  }
}

if (-not (Test-Command "docker")) {
  throw "docker is not available on PATH. Start Docker Desktop and retry."
}

if (-not (Test-Path $ComposeFile)) {
  throw "Compose file not found: $ComposeFile"
}

if (-not (Test-Path $EnvFile)) {
  Write-Host ".env not found. Create it from .env.example before starting dev services." -ForegroundColor Yellow
  Write-Host "PowerShell: Copy-Item .env.example .env" -ForegroundColor Yellow
}

$envValues = Read-DotEnv $EnvFile
$httpsPort = Env-OrDefault $envValues "ONGRID_HTTP_PORT" "443"
$httpPort = Env-OrDefault $envValues "ONGRID_HTTP_REDIRECT_PORT" "80"
$grafanaPort = Env-OrDefault $envValues "GRAFANA_PORT" "3000"
$adminEmail = Env-OrDefault $envValues "ONGRID_ADMIN_EMAIL" "admin@ongrid.local"
$composeBaseArgs = @("--env-file", $EnvFile, "-f", $ComposeFile)

Push-Location $RepoRoot
try {
  Write-Step "Checking Docker"
  docker version --format "Docker {{.Server.Version}}" | Write-Host
  docker compose version | Write-Host

  if ($Pull) {
    Write-Step "Pulling compose images"
    docker compose @composeBaseArgs pull
  }

  if ($Mode -eq "full") {
    Write-Step "Starting full Ongrid compose stack"
    if ($Build) {
      docker compose @composeBaseArgs up -d --build
    } else {
      docker compose @composeBaseArgs up -d
    }
  } else {
    Write-Step "Starting Docker dependencies for local Go development"
    Ensure-DevOverride $DevOverrideFile
    $composeDevArgs = @("--env-file", $EnvFile, "-f", $ComposeFile, "-f", $DevOverrideFile)
    if (-not $KeepManagerContainer) {
      Write-Info "Stopping containerized manager/web if they are running, so local go run can own ports 8090/9100."
      Invoke-DockerComposeQuiet `
        -Args ($composeDevArgs + @("stop", "ongrid", "nginx")) `
        -WarnMessage "Could not stop ongrid/nginx cleanly; continuing because deps mode can still start dependencies."
    }

    $services = @(
      "mysql",
      "frontier",
      "qdrant",
      "loki",
      "tempo",
      "searxng",
      "prometheus",
      "grafana"
    )
    docker compose @composeDevArgs up -d --no-deps @services
  }

  Write-Step "Current compose status"
  if ($Mode -eq "deps") {
    docker compose @composeDevArgs ps
  } else {
    docker compose @composeBaseArgs ps
  }

  Write-Step "Next commands"
  if ($Mode -eq "deps") {
    Write-Host "Run the manager locally in a new PowerShell:" -ForegroundColor Green
    Write-Host "  cd $RepoRoot"
    Write-Host '  $env:ONGRID_HTTP_ADDR=":8090"'
    Write-Host '  $env:ONGRID_METRICS_ADDR=":9100"'
    Write-Host '  $env:ONGRID_DB_DIALECT="mysql"'
    Write-Host '  $env:ONGRID_DB_DSN="ongrid:ongrid@tcp(127.0.0.1:3306)/ongrid?parseTime=true&charset=utf8mb4&loc=Local"'
    Write-Host '  $env:ONGRID_PROM_ENABLED="true"'
    Write-Host '  $env:ONGRID_PROM_URL="http://127.0.0.1:9090/prometheus"'
    Write-Host '  $env:ONGRID_PROM_QUERY_URL="http://127.0.0.1:9090/prometheus"'
    Write-Host '  $env:ONGRID_LOG_QUERY_URL="http://127.0.0.1:3100"'
    Write-Host '  $env:ONGRID_TRACE_QUERY_URL="http://127.0.0.1:3200"'
    Write-Host '  $env:ONGRID_QDRANT_URL="http://127.0.0.1:6333"'
    Write-Host '  $env:ONGRID_LLM_DEFAULT_PROVIDER="deepseek"'
    Write-Host '  $env:ONGRID_DEEPSEEK_API_KEY="<read from .env or UI settings>"'
    Write-Host '  $env:ONGRID_DEEPSEEK_MODEL="deepseek-v4-flash"'
    Write-Host '  $env:ONGRID_DEEPSEEK_BASE_URL="https://api.deepseek.com/v1"'
    Write-Host '  $env:ONGRID_INVESTIGATOR_ENABLED="true"'
    Write-Host '  $env:ONGRID_INVESTIGATOR_MIN_SEVERITY="warning"'
    Write-Host "  `$env:ONGRID_GRAFANA_INTERNAL_URL=`"http://127.0.0.1:$grafanaPort/grafana`""
    Write-Host '  $env:ONGRID_FRONTIER_DISABLED="true"'
    Write-Host "  go run ./cmd/ongrid"
    Write-Host ""
    Write-Host "Optional frontend dev server:" -ForegroundColor Green
    Write-Host "  cd $RepoRoot\web"
    Write-Host "  npm run dev"
    Write-Host ""
    Write-Host "Note: deps mode disables the local manager's Frontier client in the suggested env because the compose service-bound Frontier port is not published to the Windows host." -ForegroundColor Yellow
    Write-Host "Use scripts\dev-up.ps1 -Mode full for Edge tunnel / WebShell end-to-end validation." -ForegroundColor Yellow
  } else {
    Write-Host "Full stack is containerized. Rebuild after backend/frontend changes with:" -ForegroundColor Green
    Write-Host "  scripts\dev-up.ps1 -Mode full -Build"
  }

  Write-Step "URLs"
  if ($Mode -eq "deps") {
    Write-Host "Manager API, when go run is started: http://localhost:8090"
    Write-Host "Manager metrics, when go run is started: http://localhost:9100/metrics"
    Write-Host "Vite UI, when npm run dev is started: http://localhost:5173"
  } else {
    Write-Host "Ongrid UI: https://localhost:$httpsPort"
    Write-Host "Ongrid HTTP redirect: http://localhost:$httpPort"
    Write-Host "Manager metrics: http://localhost:9100/metrics"
  }
  Write-Host "Prometheus: http://localhost:9090/prometheus"
  Write-Host "Grafana: http://localhost:$grafanaPort/grafana"
  Write-Host "Edge tunnel (full stack): localhost:40012"
  Write-Host "Admin user: $adminEmail"
} finally {
  Pop-Location
}
